# PostgreSQL database
#
# configuration file
#

common: &common
  adapter: postgresql
  username: postgres
  password:

development:
  <<: *common
  database: skialpi-dev

test:
  <<: *common
  database: 

production:
  <<: *common
  database: skialpi-prod
